# Generated by Django 3.2 on 2024-11-03 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=9)),
                ('direccion', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('presupuesto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tatuador',
            fields=[
                ('id_tatuador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('experiencia', models.IntegerField()),
                ('estilo', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('telefono', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_cita', models.DateField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=50)),
                ('duracion', models.DurationField()),
                ('descripcion', models.TextField()),
                ('hora', models.TimeField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
                ('id_tatuador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tatuador')),
            ],
        ),
    ]
