# Generated by Django 5.1.4 on 2024-12-07 02:17

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='descripcion',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(100), app.models.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=20, validators=[django.core.validators.MaxLengthValidator(20)]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=100, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=20, validators=[django.core.validators.MaxLengthValidator(20), app.models.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='presupuesto',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=9, validators=[app.models.validate_telefono]),
        ),
        migrations.AlterField(
            model_name='tatuador',
            name='email',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='tatuador',
            name='estilo',
            field=models.CharField(max_length=20, validators=[django.core.validators.MaxLengthValidator(20)]),
        ),
        migrations.AlterField(
            model_name='tatuador',
            name='experiencia',
            field=models.IntegerField(help_text='Años.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tatuador',
            name='nombre',
            field=models.CharField(max_length=20, validators=[django.core.validators.MaxLengthValidator(20), app.models.validate_nombre]),
        ),
        migrations.AlterField(
            model_name='tatuador',
            name='telefono',
            field=models.CharField(max_length=9, validators=[app.models.validate_telefono]),
        ),
    ]
